"""Initial migration.

Revision ID: 32a618fb8e56
Revises: 
Create Date: 2022-03-07 23:48:56.960039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a618fb8e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dictionary')
    op.drop_table('menu')
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('header', sa.TEXT(), nullable=True),
    sa.Column('heading', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True)
    )
    op.create_table('dictionary',
    sa.Column('eng', sa.TEXT(), nullable=True),
    sa.Column('rus', sa.TEXT(), nullable=True),
    sa.Column('story', sa.TEXT(), nullable=True),
    sa.Column('datas', sa.DATETIME(), nullable=True)
    )
    op.create_table('user',
    sa.Column('Name', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
